# -*- coding: utf-8 -*-
"""Text Generation With GPT Neo 1.5B Models

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WWsIFvyFof8-eQiGxhDxNBS0ZRPR6wNU
"""

!pip install git+https://github.com/huggingface/transformers.git

from transformers import pipeline

generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')

text = generator("artificial intelligent ", do_sample=True, min_length=50)

print(text[0]['generated_text'])